### ISSUE TITLE
1.9.5

### ISSUE THREAD

**Issue by sacredland** [michaelortmann/botnetop.mod#1]
Unfortunatly After /configure && make config && make && make install, the module don't appear to be install in the log, neither as in the /home/user/bot/modules, even if it's appear into /home/user/eggdrop-1.9.5/src/mod. There is no /home/user/bot/modules/botnetop.so created neither.

**Comment by michaelortmann** [comment]
i cannot repeat your reported bug yet:
```
eggdrop-1.9.5.tar.gz
cd eggdrop-1.9.5/src/mod
git clone https://github.com/michaelortmann/botnetop.mod.git
cd ../../
$ ./configure && make config && make && make install
[...]
$ ls -la /home/michael/eggdrop/modules/botnetop.so
-rwxr-xr-x 1 michael michael 884576 Sep 15 14:09 /home/michael/eggdrop/modules/botnetop.so
```

did you put the mod source to `src/mod/botnetop.mod` ?

**Comment by sacredland** [comment]
Yes i did. Now with git clone it works. But even if load on multiple (6) bot. Nothing happen. Is there a console flag to set?

**Comment by michaelortmann** [comment]
Great the module now loads for you. For further help how to configure and use it, please join #eggdrop on irc.libera.chat and ask the helpful folks there.

**Comment by sacredland** [comment]
ok well, just to let you know that the mod doesnt work with botnetop.tcl anymore as variables changed. It lead to an error crashing the bot. I assume it will be the same with netbot.tcl too. Therefore maybe you can remove that part from the README. 

Till now, the helpful folks don't even know the module as it is not an official one.

**Comment by michaelortmann** [comment]
With a crash, there is all reason to reopen this PR.

Can you give me more information, how i can repeat such crash?

Which variable names changed? config variables?

**Comment by sacredland** [comment]
I used a worng version of botnetop.tcl. But, this is still not working. 

<circle> [15:13:01] Tcl error [bop_linkop]: invalid command name "isbotnetnick"
<tabb> .netbots add
 <circle> What?  You need '.help'

**Comment by michaelortmann** [comment]
i cant find the string `isbotnetnick`. not in any file in `botnetop.mod`, not in `botnetop2.23.tcl` and not in `netbots1.16.tcl`. I got a hit on https://github.com/eggheads/autoscripts/blob/master/src/chanlimit/chanlimit.tcl#L85, derived from https://ftp.eggheads.org/pub/eggdrop/scripts/1.6/netbots4.10.tar.gz but i dont see any relation to this `botnetop.mod`.

**Comment by sacredland** [comment]
in netbots.tcl (v.4.10). 

proc isbotnetnick {nick} {
  global botnet-nick
  if {[string tolower $nick] == [string tolower ${botnet-nick}]} {return 1}
  return 0
}
but not part of botnetop.mod, as you said. but that mod don't do anything, and on #eggdrop@libera they don't know your mod so can't help, so i tried botnetop.tcl & netbot.tcl & netset.tcl. lead to nothing, making the mod useless.

**Comment by michaelortmann** [comment]
sorry the mod doesnt work for you.
but i dont see a mod bug here. does it still "crash"? can you say what exactly you do and what you expect?
please unload those tcls before using the mod. i have no clue about any interaction and about those tcls and its hard to figure out what the mod problem is, if tcls are involved.
netbots is currently totally unsupported.
sorry for routing you to the wrong #eggdrop, where they also dont support those tcls.
anyway, if there is really a mod bug and you can show me, tell me how i can repeat it, i could look at it and try to fix it.

**Comment by sacredland** [comment]
just making the bots invite them/op. will simply use flag instead.
